name = "stunnas-tweaks"
compatibility_date = "2024-02-26"

[site]
bucket = "./dist"
entry-point = "."

[build]
command = "npm run build"
output_dir = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.upload]
format = "service-worker"

[env.production]
workers_dev = false
route = "stunnastweaks.pages.dev/*"

[env.staging]
workers_dev = true

[miniflare]
kv_persist = true
cache_persist = true

[dev]
port = 5173
local_protocol = "http"
